---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-1-config
  namespace: default
data:
  default.conf: |
    server {
        listen       8081;
        server_name  localhost;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-2-config
  namespace: default
data:
  default.conf: |
    server {
        listen       8082;
        server_name  localhost;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-1-web
spec:
  selector:
    app: web-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-2-web
spec:
  selector:
    app: web-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: web-1
spec:
  containers:
  - name: nginx-1
    image: ekonser/nginx_curl
    ports:
    - containerPort: 8081
    volumeMounts:
        - name: config-vol
          mountPath: /etc/nginx/conf.d
  volumes:
    - name: config-vol
      configMap:
        name: nginx-1-config
        items:
          - key: default.conf
            path: default.conf
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: web-2
spec:
  containers:
  - name: nginx-2
    image: ekonser/nginx_curl
    ports:
    - containerPort: 8082
    volumeMounts:
        - name: config-vol
          mountPath: /etc/nginx/conf.d
  volumes:
    - name: config-vol
      configMap:
        name: nginx-2-config
        items:
          - key: default.conf
            path: default.conf